name = "Basepack Forge"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70ddc089ca1b5c49f0bd239598b73569dcee1fab7dca4afc0e25ab5d95a16281"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
