name = "Basepack Forge"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aa4a4d7da7bdc53f0167c76ef938363194919510a396505c5a341dd68a2db68"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
