name = "Basepack Forge"
author = "verbina29"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3de27c5db352f6ea48548c6d05b6bf1149ee1874280e3e9278b1df8964046bb3"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
